name: dbug_vpn
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  get_storage: ^2.1.1
  url_launcher: ^6.3.1
  package_info_plus: ^8.2.1
  share_plus: ^10.1.4
  device_info_plus: ^11.3.0
  dio: ^5.7.0
  flutter_svg: ^2.0.17
  hive_flutter: ^1.1.0
  http: ^1.3.0
  intl: ^0.19.0
  country_code_picker: ^3.2.0
  firebase_messaging: ^15.2.2
  firebase_core: ^3.11.0
  firebase_crashlytics: ^4.3.2
  google_mobile_ads: ^5.3.1
  unity_ads_plugin: ^0.3.23
  onepref: ^0.0.17
  otp_autofill: ^4.1.0
  pin_code_fields: ^8.0.1
  flutter_inappwebview: ^6.1.5
  facebook_audience_network: ^1.0.1
  awesome_notifications: ^0.9.3+1 # don't update this library other wise got error from vpnLib
  flutter_phoenix: ^1.1.1
  permission_handler: ^11.3.1
  ironsource_mediation: ^3.1.0
  flutterwave_standard: ^1.0.8
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/font/outfit_light.ttf
          weight: 300
        - asset: assets/font/outfit_regular.ttf
          weight: 400
        - asset: assets/font/outfit_medium.ttf
          weight: 500
        - asset: assets/font/outfit_semi_bold.ttf
          weight: 600
        - asset: assets/font/outfit_bold.ttf
          weight: 700